# pyproject.toml

[build-system]
requires = ["setuptools>=84.0.0", "cython>=3.2.5", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "grikod2"
version = "1.1.6"
dynamic = ["keywords", "maintainers"]
license = "MIT"

authors = [
    { name="Mehmet Keçeci", email="enfo@tuta.io" },
]
description = "Binary to Gray code conversion package for efficient data encoding."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
]

dependencies = [
    "numpy",
]

[package.build-dependencies]
setuptools = ">=84.0.0"
cython = ">=3.0.0"
compilers = "*"  # Linux ortamında Cython kodunu derlemek için GCC/Clang kurar

[tool.pixi.package.build-dependencies]
setuptools = ">=84.0.0"
cython = ">=3.0.0"
compilers = "*"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]

[tool.setuptools.packages.find]
include = ["grikod2*"]
exclude = ["binder", "build*", "content", "data", "dist", "dist*", "docs", "docs*", "examples*", "examples", "notebooks", "tests", "tests*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.py", "*.pyx", "*.pyi", "*.pyd", "*.so"]  # .pyx ekleyin

[project.urls]
Homepage = "https://github.com/WhiteSymmetry/grikod2"
Repository = "https://github.com/WhiteSymmetry/grikod2"

[dependency-groups]
build = [
    "setuptools>=84.0.0",
    "cython>=3.2.5",
    "numpy"
]
